### ISSUE TITLE
Does "epoch" mean UNIX epoch?

### ISSUE THREAD

**Issue by marcospassos** [brick/date-time#1]
I'd like to suggest specifying which epoch the library uses as the reference.

**Comment by marcospassos** [comment]
Epoch is an instant in time chosen as the origin of a particular era. Technically, it ambiguous unless you specify the era and the underlying calendar system.

https://en.wikipedia.org/wiki/Epoch_(reference_date)

**Comment by BenMorel** [comment]
It is unambiguously documented in some places:

https://github.com/brick/date-time/blob/master/src/Instant.php#L17

But it does just say "epoch" in other places indeed. Feel free to open a PR if you wish!

**Comment by BenMorel** [comment]
Closing for now, please feel free to open a PR if you feel like `1970-01-01T00:00:00Z` should be explicitly documented in some places.
