### ISSUE TITLE
Retrieving Instant from ISO DateTime string

### ISSUE THREAD

**Issue by jakeworrall** [brick/date-time#14]
Hi,

I am trying to retrieve an instant from an ISO datetime string, eg "2019-05-10T11:00:00Z".

I have found a way to do this using the `IsoParsers::offsetDateTime()` parser but it seems a bit longwinded:

```
$parseResult = IsoParsers::offsetDateTime()->parse($dateTimeString);
$instant = ZonedDateTime::from($parseResult)->getInstant();
```

Is this the best way to do this?

Thanks,
Jake

**Comment by BenMorel** [comment]
Hi Jake, yes there is 👍 

```php
$instant = ZonedDateTime::parse('2019-05-10T11:00:00Z')->getInstant();
```
