### ISSUE TITLE
Week class ?

### ISSUE THREAD

**Issue by palansher** [brick/date-time#39]
Hello!

For my project, I made the "week class". It is useful when working on projects with active weeks periods in accounting.
 The idea - is not to use time range for week (first day-last day), but use object and store the week in db in one field, as integer week number (1,2 .. 654887). It is very likely as a year has a number (2021 for instance).
A week object inself stores first-last dates, some suitable methods and can be easy calculable: i.e. get a week minus three weeks from the certain week (without manipulation with date/dime objects) ... 
I was surprised that nobody find it convenient before me :)

**Comment by BenMorel** [comment]
Hi, did you check [YearWeek](https://github.com/brick/date-time/blob/master/src/YearWeek.php)?

**Comment by BenMorel** [comment]
Thank you! Closing this one.

> It is doesn't support methods a-la "getFirst(Last)DateofPeriod" but also adaptable for my needs.

Please feel free to open an issue if you want to request this feature (with explanation & examples).
