### ISSUE TITLE
Named Constructors for TimeZone

### ISSUE THREAD

**Issue by pscheit** [brick/date-time#54]
Would you be open to add some Named Constructors just for Convenience?

TimeZone::UTC() === TimeZone::parse('UTC')
TimeZone::EuropeBerlin() === TimeZone::parse('Europe/Berlin')

etc, pp? That way i dont remember which string needs to be passed to parse

At least the on with UTC seems to be very handy?

**Comment by pscheit** [comment]
oooh. don't mind me, you added it, i didn't see because smallcaps

**Comment by BenMorel** [comment]
I think it makes sense for UTC as it is universally available, but other factory methods may depend on the version of the timezonedb, so I don't think we should hardcode them!
