### ISSUE TITLE
[performance] Optimizing LocalDate::plusDays() method

### ISSUE THREAD

**Issue by gnutix** [brick/date-time#78]
Hello @BenMorel,

As you've noticed, I'm focusing on some performance aspects of this library.

There's one operation we do very often in our codebase : `LocalDate::plusDays(1)`. Mostly because we often need to convert "date and time" intervals (with an exclusive end) to "date only" intervals (with an inclusive end), and this is done by calling `plusDays(1)` on the end of the interval.

I have a Blackfire inspection that shows that for ~400'000 calls to `plusDays()` in a request, it takes 11.5 seconds, of which :

* 0.5 seconds is spent in the method's code itself
* 4.27 seconds is spent in `LocalDate::toEpochDay`, of which 2.68 seconds in the method's code itself and 1.25 seconds in `intdiv`.
* 6.69 seconds is spent in `LocalDate::ofEpochDay`, of which 4.77 seconds in the method's code itself and 1.92 seconds in `intdiv`.

I don't think there's much that can be done regarding `intdiv`, as it's a native PHP function. And obviously, we can't use a cache to improve performances, as the `LocalDate` we call `plusDays(1)` from will widely vary (aka represent different dates).

So, I'm left wondering if there's maybe something there that could be done within `toEpochDay` and `ofEpochDay` themselves ? But looking at the code, I'm quite lost regarding what could actually be improved, except trying to reduce the number of mathematical operations that are done while keeping all the edge-cases they have to deal with...

Or could it be simplified by having a separate method that does specifically `plusOneDay` (and not "N" days) ?

I'm eager to read your thoughts and insights about this. Thanks !
gnutix

**Comment by gnutix** [comment]
We've worked on a patch for `LocalDate::plusDays()` that specifically improves performances when giving `1` as argument. Here it is : 

```diff
diff --git a/src/LocalDate.php b/src/LocalDate.php
index c3abed9..6505e24 100644
--- a/src/LocalDate.php
+++ b/src/LocalDate.php
@@ -470,6 +470,12 @@ final class LocalDate implements JsonSerializable
             return $this;
         }
 
+        if ($days === 1) {
+            return $this->day >= 28 && $this->day === $this->getLengthOfMonth()
+                ? new self($this->year + intdiv($this->month, 12), ($this->month % 12) + 1, 1)
+                : new self($this->year, $this->month, $this->day + 1);
+        }
+
         return LocalDate::ofEpochDay($this->toEpochDay() + $days);
     }
 
```

Local PHP script-based benchmark shows that for 10'000'000 iterations (from `2023-09-15` to `29402-10-11`) takes in average 25 seconds without the patch and 5 seconds with it. Adding the patch does not change the results if the input argument is something else than `1` (or a very negligible amount).

I understand this is quite a specific patch, mostly related to our own use case in our code base, but I still think it might benefit users of this library. If you're OK, I'll propose a PR. Otherwise, we'll use a composer patch in our project.

**Comment by BenMorel** [comment]
> So, I'm left wondering if there's maybe something there that could be done within toEpochDay and ofEpochDay themselves ? But looking at the code, I'm quite lost regarding what could actually be improved, except trying to reduce the number of mathematical operations that are done while keeping all the edge-cases they have to deal with...

This code is a port from the Java version, and is a bit obscure I agree. I don't know if much can be done to improve it, but I think that the `plusDays(1)` optimization is a good compromise!
