### ISSUE TITLE
Consider making value classes final

### ISSUE THREAD

**Issue by joshdifabio** [brick/date-time#8]
The value classes should really be final.

**Comment by BenMorel** [comment]
Good point, I usually make my classes final unless they are explicitly meant to be extended, not sure why I did not do this at the time.

**Comment by BenMorel** [comment]
Done in 99c1f65d542360dc8ef49d07b962afb62f14ef18, will be released as 0.2.0 once #10 is complete.

**Comment by natebrunette** [comment]
I was going to suggest adding better support for extending classes like `ZonedDateTime`. I'd like to be able to extend it, and it would be helpful if `static` was used instead of the class name. I want to be able to augment the class with app-specific methods, but currently can't without copying most of it.

**Comment by joshdifabio** [comment]
These are value objects -- you shouldn't really be extending them. 

Testing equality is fundamental on VOs and being able to subclass a VO complicates or breaks that feature.

**Comment by BenMorel** [comment]
I'm on the same page as @joshdifabio here; you should favour composition over inheritance, i.e. create your class from scratch, wrapping an instance of `ZonedDateTime` and delegating parts of the work to it. Yes, some methods will just be proxies to the underlying object methods, but you'll expose only the methods you need, and are free to change their behaviour as you wish (like making them return an instance of *your* class).

I'm usually against extending classes from a library, unless they've been specifically designed for this purpose. In addition to not being good practice, extendable classes add to the maintenance burden by adding backwards compatibility promises to internal code.

Maybe if you tell us a bit more about your use case, we can help you refactor it towards composition. What are you extending `ZonedDateTime()` for?

**Comment by BenMorel** [comment]
Done in 9625e8408b7136b2447a61e7a3d046caede0f573 and released in [0.2.0](https://github.com/brick/date-time/releases/tag/0.2.0).
