### ISSUE TITLE
Broken badge on README

### ISSUE THREAD

**Issue by BenMorel** [brick/date-time#88]
Since #53, the CI badge on the README is broken: https://github.com/brick/date-time/workflows/CI/badge.svg

This is because we don't have a single `CI` workflow anymore, but [3 workflows](https://github.com/brick/date-time/tree/0.5.3/.github/workflows):

- `Coding Style`
- `Static Analysis`
- `Tests`

Each having its own badge:

- https://github.com/brick/date-time/workflows/Coding%20Style/badge.svg
- https://github.com/brick/date-time/workflows/Static%20Analysis/badge.svg
- https://github.com/brick/date-time/workflows/Tests/badge.svg

@tigitz Do you know of a way to get a single badge for all 3 workflows?

**Comment by tigitz** [comment]
AFAIU, there doesn't seem to be a way to aggregate those statuses into a single badge, no.

Unless we put all the jobs into a single "CI" workflow and generate a badge from this.

**Comment by BenMorel** [comment]
I changed the badge to point to the Tests workflow only some time ago in 1879abac236b09a33ae7b40827e9395bccb8b6a4. This is good enough for now, we'll revisit this later if needed.

Closing to avoid polluting issues for too long.
