### ISSUE TITLE
Year::toISOString() not conformation to ISO 8601

### ISSUE THREAD

**Issue by andreaswolf** [brick/date-time#89]
According to Wikipedia and https://github.com/moment/moment/issues/3842#issuecomment-287738049 (I don't have access to the norm myself, so I need to quote other sources), the year part of any date in ISO 8601 should have at least four digits, with leading zeros for years < 1000. The `PATTERN` constant in `YearField` also reflects this.

The new method `toISOString()`, however, just does a (string) on the integer member `$year`. IMO, this should be handled similar to `LocalDate::toISOString()`.

**Comment by BenMorel** [comment]
I think you're right indeed. We need to copy the year logic from `YearMonth` / `LocalDate`.
Do you want to open a PR?

**Comment by andreaswolf** [comment]
> I think you're right indeed. We need to copy the year logic from `YearMonth` / `LocalDate`. Do you want to open a PR?

Just did that. I had a patch applied locally already, it was just missing tests.
