### ISSUE TITLE
Add `DefaultClock::travelForwards(Duration)`

### ISSUE THREAD

**Issue by francislavoie** [brick/date-time#91]
Currently, I have to write code like this to travel forwards by some nanos (to mimic `usleep`):

```php
DefaultClock::travel(Instant::now()->plus(Duration::ofNanos($delayNanos)));
```

It would be nicer if I could write:

```php
DefaultClock::travelForwards(Duration::ofNanos($delayNanos));
```

Would this be an acceptable addition?

**Comment by BenMorel** [comment]
Hi @francislavoie,

Yes, I think this is a reasonable addition, together with its `travelBackwards()` counterpart.
What about `travelForward` vs `travelForwards` though? As I understand this is an AE vs BE issue, what's your take on this?

**Comment by francislavoie** [comment]
👍 sounds good to me, you're right I think `Forward` is probably more correct.

Somewhat off topic, I was also missing a function on `Instant` that would return seconds with millis as  a float; there's only seconds int or millis int but no seconds float which is typically nicer for presentation in a log message or whatever. I'm not sure what that method should be called though. Admittedly this can lose precision because of course floats aren't perfect but I think it's good enough for many situations.

**Comment by BenMorel** [comment]
Yes, please open a new issue to discuss this :wink:

**Comment by francislavoie** [comment]
Regarding that last bit about seconds float, I just found `->toDecimal()` which does what I wanted. So scratch that :sweat_smile: 

I opened #92 to solve this
