### ISSUE TITLE
`LocalDate::parse(...)` does not recognise ISO-8601

### ISSUE THREAD

**Issue by joelbutcher** [brick/date-time#93]
Trying to parse the following:

```php
\Brick\DateTime\LocalDate::parse('2024-03-11T00:00:00.000Z');
```

results in:

```
Brick\DateTime\Parser\DateTimeParseException  Failed to parse "2024-03-11T00:00:00.000Z"
```

**Comment by BenMorel** [comment]
Hi, your string is the ISO 8601 representation of a date-time with a timezone, which is represented in brick/date-time by `ZonedDateTime`:

```php
\Brick\DateTime\ZonedDateTime::parse('2024-03-11T00:00:00.000Z'); // works
```

If you need only the date part (a `LocalDate`), you can call `ZonedDateTime::getDate()`:

```php
\Brick\DateTime\ZonedDateTime::parse('2024-03-11T00:00:00.000Z')->getDate();
```

Or pass just the date part to `LocalDate::parse()`:

```php
\Brick\DateTime\LocalDate::parse('2024-03-11'); // works
```
