### ISSUE TITLE
Year::atMonth() should accept a Month

### ISSUE THREAD

**Issue by gnutix** [brick/date-time#94]
Hello there,

I'm in the process of upgrading to 0.6, and I've noticed this in the changelog : 

> YearWeek: the atDay() method now accepts a DayOfWeek instance, passing an integer is deprecated

I'm surprised that the same wasn't done for `atMonth`. I found a usage in our code I expected to just work, but I had to add `->value` instead to get the int.

Is it something that was simply forgotten ? Or is there a reason ?
gnutix

**Comment by BenMorel** [comment]
I think you mean:

>Year::atMonth() should accept a ~YearMonth ?~ `int`?

Then most definitely yes, it was forgotten. Do you want to open a PR?

**Comment by gnutix** [comment]
Yes sorry, I meant a `Month` indeed. Example : 

```
Year::parse('2024')->atMonth(Month::JANUARY->value)->getFirstDay(); // equals 2024-01-01
```

**Comment by gnutix** [comment]
PR done : https://github.com/brick/date-time/pull/95
